INSERT INTO FLYDB_CREATE_T(COLUMN1) VALUES('test1');
INSERT INTO FLYDB_CREATE_T(COLUMN1) VALUES('test2');
INSERT INTO FLYDB_CREATE_T(COLUMN1) VALUES('test3');
INSERT INTO FLYDB_CREATE_T(COLUMN1) VALUES('test4');
INSERT INTO FLYDB_CREATE_T(COLUMN1) VALUES('test5');