INSERT INTO FLYDB_CREATE_T1_1(COLUMN1) VALUES('test1');
INSERT INTO FLYDB_CREATE_T1_1(COLUMN1) VALUES('test2');
INSERT INTO FLYDB_CREATE_T1_1(COLUMN1) VALUES('test3');
INSERT INTO FLYDB_CREATE_T1_1(COLUMN1) VALUES('test4');
INSERT INTO FLYDB_CREATE_T1_1(COLUMN1) VALUES('test5');

ALTER TABLE FLYDB_CREATE_T1_1 
    ALTER COLUMN COLUMN1 TYPE VARCHAR(100);